<form wire:submit="save" class="space-y-5">
    <header class="flex flex-wrap justify-between items-center gap-3">
        <div><a href="{{ route('purchases.index') }}" class="text-xs text-primary">{{ __('purchasing.purchases') }}</a><h1 class="text-2xl font-bold mt-1">{{ __($publicId ? 'purchasing.edit_purchase' : 'purchasing.new_purchase') }}</h1></div>
        <span class="text-xs font-bold bg-surface-blue text-primary px-3 py-2 rounded-control">{{ __('purchasing.draft') }}</span>
    </header>
    <p class="p-3 bg-info-bg text-info text-sm rounded-control">{{ __('purchasing.draft_notice') }}</p>
    @if($errors->any())<div role="alert" class="p-3 bg-danger-bg text-danger text-sm rounded-control"><ul class="list-disc ps-4">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    @if($duplicateWarning)<p role="status" class="p-3 bg-warning-bg text-warning text-sm rounded-control">{{ __('purchasing.duplicate_vendor_invoice') }}</p>@endif
    <section class="bg-surface border border-border rounded-card p-4 grid sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <div class="sm:col-span-2"><label for="purchase-vendor" class="block text-xs font-bold mb-1.5">{{ __('purchasing.vendor') }}</label><select id="purchase-vendor" wire:model.live="vendor_id" required class="w-full h-11 px-3 border border-border rounded-control text-sm"><option value="">{{ __('purchasing.select_vendor') }}</option>@foreach($vendors as $vendor)<option value="{{ $vendor->id }}">{{ $vendor->displayName() }}</option>@endforeach</select></div>
        <div class="sm:col-span-2"><label for="supplier-number" class="block text-xs font-bold mb-1.5">{{ __('purchasing.vendor_invoice_number') }}</label><input id="supplier-number" wire:model.live.debounce.400ms="vendor_invoice_number" maxlength="128" dir="ltr" class="w-full h-11 px-3 border border-border rounded-control text-sm" /></div>
        @foreach(['purchase_date' => 'purchase_date', 'due_date' => 'due_date'] as $field => $label)<div><label for="purchase-{{ $field }}" class="block text-xs font-bold mb-1.5">{{ __('purchasing.'.$label) }}</label><input id="purchase-{{ $field }}" type="date" wire:model="{{ $field }}" class="w-full min-w-0 h-11 px-3 border border-border rounded-control text-sm" @if($field === 'purchase_date') required @endif /></div>@endforeach
        <div><label for="purchase-currency" class="block text-xs font-bold mb-1.5">{{ __('purchasing.currency') }}</label><select id="purchase-currency" wire:model.live="currency_code" class="w-full h-11 px-3 border border-border rounded-control text-sm">@foreach($currencies as $currency)<option value="{{ $currency->currency_code }}">{{ $currency->currency_code }}</option>@endforeach</select></div>
        <div><label for="purchase-rate" class="block text-xs font-bold mb-1.5">{{ __('purchasing.exchange_rate') }}</label><input id="purchase-rate" wire:model.live.debounce.400ms="exchange_rate" inputmode="decimal" dir="ltr" class="w-full h-11 px-3 border border-border rounded-control text-sm" /></div>
        <div class="sm:col-span-2"><label for="purchase-warehouse" class="block text-xs font-bold mb-1.5">{{ __('purchasing.receiving_warehouse') }}</label><select id="purchase-warehouse" wire:model="warehouse_id" required class="w-full h-11 px-3 border border-border rounded-control text-sm"><option value="">{{ __('purchasing.select_warehouse') }}</option>@foreach($warehouses as $warehouse)<option value="{{ $warehouse->id }}">{{ $warehouse->displayName() }}</option>@endforeach</select></div>
        <div class="sm:col-span-2"><label for="purchase-locale" class="block text-xs font-bold mb-1.5">{{ __('purchasing.document_language') }}</label><select id="purchase-locale" wire:model="document_locale" class="w-full h-11 px-3 border border-border rounded-control text-sm">@foreach($languages as $language)<option value="{{ $language->locale }}">{{ __('purchasing.locale_'.$language->locale) }}</option>@endforeach</select></div>
    </section>
    <section class="space-y-3">
        <div class="flex flex-wrap justify-between items-center gap-3"><h2 class="font-bold">{{ __('purchasing.purchase_lines') }}</h2><button type="button" wire:click="addLine" class="h-11 px-3 text-primary border border-border rounded-control text-sm font-bold">{{ __('purchasing.add_line') }}</button></div>
        <label for="purchase-product-search" class="sr-only">{{ __('purchasing.search_products') }}</label><input id="purchase-product-search" type="search" wire:model.live.debounce.300ms="productSearch" placeholder="{{ __('purchasing.search_products') }}" class="w-full h-11 px-3 border border-border bg-surface rounded-control text-sm" />
        @foreach($lines as $index => $line)
            <article wire:key="purchase-line-{{ $index }}-{{ $line['product_id'] ?? 'new' }}" class="bg-surface border border-border rounded-card p-4 space-y-3">
                <div class="flex justify-between items-center gap-2"><h3 class="text-xs font-bold">{{ __('purchasing.line') }} <bdi>{{ $index + 1 }}</bdi></h3><button type="button" wire:click="removeLine({{ $index }})" class="h-10 px-3 text-danger text-xs">{{ __('purchasing.remove_line') }}</button></div>
                <div class="grid grid-cols-2 lg:grid-cols-12 gap-3">
                    <div class="col-span-2 lg:col-span-4"><label for="line-product-{{ $index }}" class="block text-xs text-text-secondary mb-1">{{ __('purchasing.product') }}</label><select id="line-product-{{ $index }}" wire:change="selectProduct({{ $index }}, $event.target.value)" class="w-full h-11 px-2 border border-border rounded-control text-sm"><option value="">{{ __('purchasing.select_product') }}</option>
                        @if(!empty($line['product_id']) && !$products->contains('id', $line['product_id']))<option selected value="{{ $line['product_id'] }}">{{ $line['item_description'] }}</option>@endif
                        @foreach($products as $product)<option value="{{ $product->id }}" @selected(($line['product_id'] ?? null) == $product->id)>{{ $product->displayName() }} {{ $product->sku }}</option>@endforeach
                    </select></div>
                    <div class="lg:col-span-2"><label for="line-unit-{{ $index }}" class="block text-xs text-text-secondary mb-1">{{ __('purchasing.unit') }}</label><select id="line-unit-{{ $index }}" wire:change="changeUnit({{ $index }}, $event.target.value)" class="w-full h-11 px-2 border border-border rounded-control text-sm" @disabled(empty($line['product_id']))><option value="">{{ __('purchasing.select_unit') }}</option>@foreach($unitOptions[$index] ?? [] as $unit)<option value="{{ $unit->id }}" @selected(($line['product_unit_id'] ?? null) == $unit->id)>{{ $unit->unit->name() }}</option>@endforeach</select></div>
                    @foreach(['quantity', 'unit_cost'] as $field)<div class="lg:col-span-2"><label for="line-{{ $field }}-{{ $index }}" class="block text-xs text-text-secondary mb-1">{{ __('purchasing.'.$field) }}</label><input id="line-{{ $field }}-{{ $index }}" wire:model.live.debounce.400ms="lines.{{ $index }}.{{ $field }}" inputmode="decimal" dir="ltr" class="w-full min-w-0 h-11 px-2 border border-border rounded-control text-sm" /></div>@endforeach
                    <div class="col-span-2 lg:col-span-2"><span class="block text-xs text-text-secondary mb-1">{{ __('purchasing.line_total') }}</span><output class="block h-11 px-2 py-3 text-sm font-bold bg-surface-soft rounded-control"><bdi>{{ isset($line['preview_total']) ? \App\Domain\Sales\Formatters\SalesMoneyFormatter::format($line['preview_total'], $currency_code) : '—' }} {{ $currency_code }}</bdi></output></div>
                </div>
                <div class="grid sm:grid-cols-2 lg:grid-cols-4 gap-3">
                    <div><label for="line-description-{{ $index }}" class="block text-xs text-text-secondary mb-1">{{ __('purchasing.description') }}</label><input id="line-description-{{ $index }}" wire:model="lines.{{ $index }}.item_description" maxlength="500" class="w-full h-11 px-2 border border-border rounded-control text-sm" /></div>
                    <div><label for="line-discount-type-{{ $index }}" class="block text-xs text-text-secondary mb-1">{{ __('purchasing.discount') }}</label><select id="line-discount-type-{{ $index }}" wire:model.live="lines.{{ $index }}.discount_type" class="w-full h-11 px-2 border border-border rounded-control text-sm">@foreach(['none', 'percent', 'fixed'] as $type)<option value="{{ $type }}">{{ __('purchasing.discount_'.$type) }}</option>@endforeach</select></div>
                    <div><label for="line-discount-value-{{ $index }}" class="block text-xs text-text-secondary mb-1">{{ __('purchasing.discount_value') }}</label><input id="line-discount-value-{{ $index }}" wire:model.live.debounce.400ms="lines.{{ $index }}.discount_value" dir="ltr" inputmode="decimal" class="w-full h-11 px-2 border border-border rounded-control text-sm" /></div>
                    @if($taxes->isNotEmpty())<div><label for="line-tax-{{ $index }}" class="block text-xs text-text-secondary mb-1">{{ __('purchasing.tax') }}</label><select id="line-tax-{{ $index }}" wire:model.live="lines.{{ $index }}.tax_rate_id" class="w-full h-11 px-2 border border-border rounded-control text-sm"><option value="">{{ __('purchasing.no_tax') }}</option>@foreach($taxes as $tax)<option value="{{ $tax->id }}">{{ $tax->displayName() }} ({{ \App\Domain\Sales\Formatters\SalesMoneyFormatter::format($tax->rate, 'ILS') }}%)</option>@endforeach</select></div>@endif
                </div>
                @if($expiryLines[$index] ?? false)
                    <div class="border-t border-border pt-3 space-y-3">
                        <div class="flex flex-wrap items-center justify-between gap-2"><div><h4 class="text-xs font-bold">{{ __('purchasing.receiving_intent') }}</h4><p class="text-xs text-text-secondary mt-1">{{ __('purchasing.partial_lot_hint') }}</p></div><button type="button" wire:click="addLot({{ $index }})" class="h-10 px-3 border border-border rounded-control text-primary text-xs">{{ __('purchasing.add_lot') }}</button></div>
                        @foreach($line['lots'] ?? [] as $lotIndex => $lot)
                            <div wire:key="intent-{{ $index }}-{{ $lotIndex }}" class="grid grid-cols-2 lg:grid-cols-4 gap-3 bg-surface-soft rounded-control p-3">
                                @foreach(['lot_number' => 'text', 'expiry_date' => 'date', 'quantity' => 'text'] as $field => $type)<div><label for="lot-{{ $index }}-{{ $lotIndex }}-{{ $field }}" class="block text-xs text-text-secondary mb-1">{{ __('purchasing.'.($field === 'quantity' ? 'allocated_quantity' : $field)) }}</label><input id="lot-{{ $index }}-{{ $lotIndex }}-{{ $field }}" type="{{ $type }}" wire:model="lines.{{ $index }}.lots.{{ $lotIndex }}.{{ $field }}" dir="ltr" class="w-full min-w-0 h-11 px-2 border border-border bg-surface rounded-control text-sm" /></div>@endforeach
                                <button type="button" wire:click="removeLot({{ $index }}, {{ $lotIndex }})" class="self-end h-11 px-3 text-danger text-xs">{{ __('purchasing.remove_lot') }}</button>
                            </div>
                        @endforeach
                    </div>
                @endif
            </article>
        @endforeach
    </section>
    <section class="bg-surface border border-border rounded-card p-4 grid grid-cols-2 md:grid-cols-4 gap-4">@foreach(['subtotal', 'discount', 'tax', 'total'] as $field)<div><span class="text-xs text-text-secondary">{{ __('purchasing.'.$field) }}</span><p class="font-bold mt-1"><bdi>{{ isset($totals[$field]) ? \App\Domain\Sales\Formatters\SalesMoneyFormatter::format($totals[$field], $currency_code) : '—' }} {{ $currency_code }}</bdi></p></div>@endforeach</section>
    <div><label for="purchase-notes" class="block text-xs font-bold mb-1.5">{{ __('purchasing.notes') }}</label><textarea id="purchase-notes" wire:model="notes" rows="3" class="w-full border border-border rounded-control bg-surface p-3 text-sm"></textarea></div>
    <footer class="flex flex-wrap gap-3"><button type="submit" wire:loading.attr="disabled" wire:target="save" class="h-11 px-5 bg-primary text-white font-bold text-sm rounded-control">{{ __('purchasing.save_draft') }}</button><a href="{{ route('purchases.index') }}" class="inline-flex items-center h-11 px-4 border border-border rounded-control text-sm">{{ __('purchasing.cancel') }}</a></footer>
</form>
